version: '3'
services:

  postgres:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - devnet

networks:
  devnet:
    driver: bridge

volumes:
  pgdata:
    driver: "local"
